### ISSUE TITLE
Muted channels/servers show as unread

### ISSUE THREAD

**Issue by yoshiask** [UnicordDev/Unicord#57]
Unread indicators are always shown if there are unread messages, even if those channels/servers are muted.

This might also affect notifications for muted channels/servers, but I can't confirm that yet.

**Comment by WamWooWam** [comment]
This may have been fixed by 1.7.0, please let me know if it has!

**Comment by Jimmy-Blue** [comment]
The bug still present on some server. For example, Unicord server. Even though every channels are read, it still shows that Unicord server is unread.

**Comment by WamWooWam** [comment]
read/unread handling has been completely rewritten since this issue was filed so i'm gonna assume it's fixed now
